<?php
$data = array (
  3 => 
  array (
    'cat_id' => '3',
    'cat_name' => '尿裤湿巾',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '3',
    'name' => '尿裤湿巾',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => '拉拉裤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '19',
    'name' => '拉拉裤',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => '婴儿湿巾',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '17',
    'name' => '婴儿湿巾',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => '纸尿裤',
    'measure_unit' => '',
    'parent_id' => '3',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '18',
    'name' => '纸尿裤',
  ),
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '哺乳喂养',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '哺乳喂养',
  ),
  16 => 
  array (
    'cat_id' => '16',
    'cat_name' => '奶嘴',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '16',
    'name' => '奶嘴',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '吸奶器',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '13',
    'name' => '吸奶器',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '哺喂餐具',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '14',
    'name' => '哺喂餐具',
  ),
  15 => 
  array (
    'cat_id' => '15',
    'cat_name' => '奶瓶',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '15',
    'name' => '奶瓶',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '母婴专区',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '1',
    'name' => '母婴专区',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '保健强身',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '6',
    'name' => '保健强身',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '营养滋补',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '7',
    'name' => '营养滋补',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '纤体修身',
    'measure_unit' => '',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '8',
    'name' => '纤体修身',
  ),
  5 => 
  array (
    'cat_id' => '5',
    'cat_name' => '寝具服饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '5',
    'name' => '寝具服饰',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => '女童服饰',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '22',
    'name' => '女童服饰',
  ),
  23 => 
  array (
    'cat_id' => '23',
    'cat_name' => '童鞋',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '23',
    'name' => '童鞋',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => '儿童泳装',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '20',
    'name' => '儿童泳装',
  ),
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => '婴幼儿家纺',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '24',
    'name' => '婴幼儿家纺',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => '男童服饰',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '21',
    'name' => '男童服饰',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '洗护清洁',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '洗护清洁',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '洗发沐浴',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '12',
    'name' => '洗发沐浴',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '衣物洗护',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '9',
    'name' => '衣物洗护',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '口腔护理',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '10',
    'name' => '口腔护理',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '卫生护理',
    'measure_unit' => '',
    'parent_id' => '2',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '11',
    'name' => '卫生护理',
  ),
);
?>